;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        indent-for-tab-command
        kill-region
        ruby-end-space
        ruby-tools-clear-string
        ruby-tools-to-double-quote-string
        ))

(setq mc/cmds-to-run-once
      '(
        ))
